version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: "Europe/Oslo"
    ignore:
      - dependency-name: "@types/node"
        versions:
          - "25"
          - "26"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 20
    groups:
      react:
        patterns:
          - "react"
          - "@types/react"
          - "react-cookie"
          - "react-dom"
          - "@types/react-dom"
          - "react-router"
          - "@types/react-router"
      navikt:
        patterns:
          - "@navikt/aksel-icons"
          - "@navikt/ds-css"
          - "@navikt/ds-react"
          - "@navikt/fnrvalidator"
          - "@navikt/nav-dekoratoren-moduler"
          - "@navikt/oasis"
      familie:
        patterns:
          - "@navikt/familie-form-elements"
          - "@navikt/familie-http"
          - "@navikt/familie-logging"
          - "@navikt/familie-skjema"
          - "@navikt/familie-typer"
      tools:
        patterns:
          - "@nais/apm"
          - "@axe-core/react"
          - "@vercel/nft"
          - "husky"
          - "lint-staged"
          - "@portabletext/react"
          - "@portabletext/toolkit"
          - "@portabletext/types"
          - "@sanity/client"
          - "ramda"
      server:
        patterns:
          - "compression"
          - "cookie-parser"
          - "@types/cookie-parser"
          - "cors"
          - "@types/cors"
          - "express"
          - "@types/express"
          - "express-rate-limit"
          - "http-proxy-middleware"
          - "mustache-express"
          - "@types/mustache-express"
          - "xss"
      utils:
        patterns:
          - "dotenv"
          - "unleash-client"
          - "axios"
          - "date-fns"
          - "i18n-iso-countries"
          - "styled-components"
          - "uuid"
      build-test-validate:
        patterns:
          - "@types/node"
          - "ts-essentials"
          - "typescript"
          - "@biomejs/biome"
          - "@testing-library/dom"
          - "@testing-library/jest-dom"
          - "@testing-library/react"
          - "@vitejs/plugin-react"
          - "vite"
          - "jsdom"
          - "msw"
          - "vitest"
          - "vitest-mock-extended"
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      patch-updates:
        update-types:
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 4
