export enum OmBarnaDineSpørsmålId {
    erNoenAvBarnaFosterbarn = 'er-noen-av-barna-fosterbarn',
    hvemErFosterbarn = 'hvem-er-fosterbarn',
    oppholderBarnSegIInstitusjon = 'oppholder-barn-seg-i-institusjon',
    hvemOppholderSegIInstitusjon = 'hvem-oppholder-seg-i-institusjon',
    erBarnAdoptert = 'er-barn-adoptert',
    hvemErAdoptert = 'hvem-er-adoptert',
    søktAsylForBarn = 'søkt-asyl-for-barn',
    hvemErSøktAsylFor = 'hvem-er-søkt-asyl-for',
    barnOppholdtSegTolvMndSammenhengendeINorge = 'tolv-mnd-sammenhengende-i-norge',
    hvemTolvMndSammenhengendeINorge = 'hvem-tolv-mnd-sammenhengende-i-norge',
    mottarKontantstøtteForBarnFraAnnetEøsland = 'kontantstøtte-fra-annet-eøsland',
    hvemKontantstøtteFraAnnetEøsland = 'hvem-mottar-kontantstøtte-eøsland',
    harEllerTildeltBarnehageplass = 'har-eller-tildelt-barnehageplass',
    hvemBarnehageplass = 'hvem-barnehageplass',
    erFolkeregAvdødEktefelleForelder = 'er-folkeregistrert-avdød-ektefelle-forelder',
    erFolkeregAvdødPartnerForelder = 'er-folkeregistrert-avdød-partner-forelder',
    hvemAvdødPartner = 'hvem-er-avdød-partner-forelder-til',
}
