export enum EBarnehageplassPeriodeBeskrivelse {
    HAR_BARNEHAGEPLASS_NÅ = 'HAR_BARNEHAGEPLASS_NÅ',
    HATT_BARNEHAGEPLASS_TIDLIGERE = 'HATT_BARNEHAGEPLASS_TIDLIGERE',
    TILDELT_BARNEHAGEPLASS_I_FREMTIDEN = 'TILDELT_BARNEHAGEPLASS_I_FREMTIDEN',
}
