apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ks-soknad
  namespace: teamfamilie
  labels:
    team: teamfamilie
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "25M"
spec:
  image: {{ image }}
  team: teamfamilie
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  port: 9000
  liveness:
    path: /internal/isAlive
    initialDelay: 5
  readiness:
    path: /internal/isReady
    initialDelay: 5
  ingresses:
    - "https://familie-ks-soknad.dev.nav.no/familie/kontantstotte/soknad"
  accessPolicy:
    outbound:
      rules:
        - application: familie-ba-soknad-api
      external:
        - host: "www-q1.nav.no"
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
  envFrom:
    - secret: ks-soknad
    - configmap: loginservice-idporten
  env:
    - name: BASE_PATH
      value: {{base_path}}
  secureLogs:
    enabled: true
