export enum OmBarnetSpørsmålsId {
    utbetaltForeldrepengerEllerEngangsstønad = 'utbetalt-foreldrepenger-eller-engangsstønad',
    planleggerÅBoINorge12Mnd = 'barn-planlegger-å-bo-sammenhengende-i-norge-12mnd',
    pågåendeSøknadFraAnnetEøsLand = 'pågående-søknad-fra-annet-eøsland',
    pågåendeSøknadHvilketLand = 'pågående-søknad-hvilket-land',
    mottarEllerMottokEøsKontantstøtte = 'mottar-eller-mottok-eøs-kontantstøtte',
    andreForelderNavn = 'andre-forelder-navn',
    andreForelderKanIkkeGiOpplysninger = 'andre-forelder-kan-ikke-gi-opplysninger',
    andreForelderFnr = 'andre-forelder-fødsels-/dnummer',
    andreForelderFnrUkjent = 'andre-forelder-fødsels-/dnummer-ukjent',
    andreForelderFødselsdato = 'andre-forelder-fødselsdato',
    andreForelderFødselsdatoUkjent = 'andre-forelder-fødselsdato-ukjent',
    andreForelderYrkesaktivFemÅr = 'andre-forelder-yrkesaktiv-fem-år',
    andreForelderArbeidUtlandet = 'andre-forelder-arbeid',
    andreForelderArbeidUtlandetEnke = 'andre-forelder-arbeid-enke',
    andreForelderPensjonUtland = 'andre-forelder-pensjon-utland',
    andreForelderPensjonUtlandEnke = 'andre-forelder-pensjon-utland-enke',
    borFastMedSøker = 'bor-barnet-fast-med-deg',
    sammeForelderSomAnnetBarn = 'samme-forelder-som-annet-barn',
    andreForelderUtenlandsoppholdUtenArbeid = 'andre-forelder-utenlandsopphold',
    andreForelderUtenlandsoppholdUtenArbeidGjenlevende = 'andre-forelder-utenlandsopphold-gjenlevende',
}
