export enum EUtenlandsoppholdÅrsak {
    FLYTTET_PERMANENT_TIL_NORGE = 'FLYTTET_PERMANENT_TIL_NORGE',
    FLYTTET_PERMANENT_FRA_NORGE = 'FLYTTET_PERMANENT_FRA_NORGE',
    OPPHOLDER_SEG_UTENFOR_NORGE = 'OPPHOLDER_SEG_UTENFOR_NORGE',
    HAR_OPPHOLDT_SEG_UTENFOR_NORGE = 'HAR_OPPHOLDT_SEG_UTENFOR_NORGE',
}
