name: Build, push, and deploy app to prod

on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - 'master'

env:
  IMAGE: ghcr.io/${{ github.repository }}/familie-ks-soknad:${{ github.sha }}
  IMAGE_LATEST: ghcr.io/${{ github.repository }}/familie-ks-soknad:latest
  BASE_PATH: /familie/kontantstotte/soknad/

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: "https://npm.pkg.github.com"
      - name: Installer node-pakker
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
          NPM_TOKEN: ${{ secrets.READER_TOKEN }}
        run: npx yarn
      - name: Kjør typecheck
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
          NPM_TOKEN: ${{ secrets.READER_TOKEN }}
        run: npx yarn typecheck
      - name: Kjør tester
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
          NPM_TOKEN: ${{ secrets.READER_TOKEN }}
        run: npx yarn test
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: "https://npm.pkg.github.com"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Bygg Docker image
        uses: docker/build-push-action@v3
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        with:
          tags: |
            ${{ env.IMAGE }}
            ${{ env.IMAGE_LATEST }}
          build-args: |
            base_path=${{ env.BASE_PATH }}
            sentry_release=${{ github.sha }}
            NPM_TOKEN=${{ secrets.READER_TOKEN }}
          secrets: |
            sentry_token=${{ secrets.SENTRY_AUTH_TOKEN }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ env.IMAGE }}
            ${{ env.IMAGE_LATEST }}
          build-args: |
            base_path=${{ env.BASE_PATH }}
            sentry_release=${{ github.sha }}
            NPM_TOKEN=${{ secrets.READER_TOKEN }}
          secrets: |
            sentry_token=${{ secrets.SENTRY_AUTH_TOKEN }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-preprod:
    name: Deploy to dev-gcp
    needs:
      - build
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: build_n_deploy/naiserator/naiserator_dev.yaml
          VAR: base_path=${{ env.BASE_PATH }}

  deploy-prod:
    name: Deploy to prod-gcp
    needs:
      - build
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: build_n_deploy/naiserator/naiserator_prod.yaml
          VAR: base_path=${{ env.BASE_PATH }}
