name: Build, push, and deploy app to dev

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'

env:
  IMAGE: ghcr.io/${{ github.repository }}/familie-ks-soknad:${{ github.sha }}
  BASE_PATH: /familie/kontantstotte/soknad/

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: "https://npm.pkg.github.com"
      - name: Installer node-pakker
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
          NPM_TOKEN: ${{ secrets.READER_TOKEN }}
        run: npx yarn
      - name: Kjør typecheck
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
          NPM_TOKEN: ${{ secrets.READER_TOKEN }}
        run: npx yarn typecheck
      - name: Kjør tester
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
          NPM_TOKEN: ${{ secrets.READER_TOKEN }}
        run: npx yarn test

  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: "https://npm.pkg.github.com"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Bygg Docker image
        uses: docker/build-push-action@v4
        env:
          DEKORATOREN_URL: "https://dekoratoren.dev.nav.no"
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        with:
          tags: ${{ env.IMAGE }}
          build-args: |
            base_path=${{ env.BASE_PATH }}
            sentry_release=${{ github.sha }}
            NPM_TOKEN=${{ secrets.READER_TOKEN }}
          secrets: |
            sentry_token=${{ secrets.SENTRY_AUTH_TOKEN }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.IMAGE }}
          build-args: |
            base_path=${{ env.BASE_PATH }}
            sentry_auth_token=${{ secrets.SENTRY_AUTH_TOKEN }}
            sentry_release=${{ github.sha }}
            NPM_TOKEN=${{ secrets.READER_TOKEN }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to dev gcp
    needs:
      - build
      - test
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: build_n_deploy/naiserator/naiserator_dev.yaml
          VAR: base_path=${{ env.BASE_PATH }}
