name: Build, push, and deploy app to prod

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - 'main'

env:
  BASE_PATH: /familie/kontantstotte/soknad/

jobs:
  test:
    name: Kjør typecheck og tester
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: "https://npm.pkg.github.com"
      - name: Installer node-pakker
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
          NPM_TOKEN: ${{ secrets.READER_TOKEN }}
        run: npx yarn
      - name: Kjør typecheck
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
          NPM_TOKEN: ${{ secrets.READER_TOKEN }}
        run: npx yarn typecheck
      - name: Kjør tester
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
          NPM_TOKEN: ${{ secrets.READER_TOKEN }}
        run: npx yarn test

  bygg:
    name: Bygg app/image og push til GitHub
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: "https://npm.pkg.github.com"
      - uses: nais/docker-build-push@v0
        id: docker-push
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        with:
          team: teamfamilie
          tag: latest
          build_args: |
            base_path=${{ env.BASE_PATH }}
            sentry_release=${{ github.sha }}
            NPM_TOKEN=${{ secrets.READER_TOKEN }}
          build_secrets:
            |
            sentry_token=${{ secrets.SENTRY_AUTH_TOKEN }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
    outputs:
      image: ${{ steps.docker-push.outputs.image }}

  deploy-preprod:
    name: Deploy til dev-gcp
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    needs:
      - bygg
      - test
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: build_n_deploy/naiserator/naiserator_dev.yaml
          VAR: base_path=${{ env.BASE_PATH }}
          IMAGE: ${{ needs.bygg.outputs.image }}

  deploy-prod:
    name: Deploy til prod-gcp
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    needs:
      - bygg
      - test
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: build_n_deploy/naiserator/naiserator_prod.yaml
          VAR: base_path=${{ env.BASE_PATH }}
          IMAGE: ${{ needs.bygg.outputs.image }}
