name: "Check for newer image versions"

on:
  workflow_dispatch:
  schedule:
    # At the end of every day
    - cron: "0 0 * * MON"

jobs:
  digest-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          persist-credentials: false
      - uses: navikt/digestabot@e4b413f1eed3c97f7fd4ffa1d05204de9944d0a9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          team: teamfamilie
          title-for-pr: 'Bumper Chainguard Docker-image til nyeste tilgjengelige versjon.'
