name: Digestabot Updates

on:
  workflow_dispatch:
  schedule:
    # At the end of every day
    - cron: "0 0 * * *"

jobs:
  digest-update:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    uses: navikt/familie-baks-gha-workflows/.github/workflows/digestabot.yaml@main
    with:
      digestabot-client-id: ${{ vars.DIGESTABOT_CLIENT_ID }}
    secrets:
      DIGESTABOT_PRIVATE_KEY: ${{ secrets.DIGESTABOT_PRIVATE_KEY }}
